# Generated by Django 4.0.5 on 2022-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
