# Generated by Django 4.0.5 on 2022-06-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_alter_profile_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(default='default.png', upload_to='profiles/'),
        ),
    ]
